### ISSUE TITLE
Hello Again! Trees don't grow!

### ISSUE THREAD

**Issue by AlexProGear** [AntMCDev/MCSkyblock#11]
There is a new issue!
Whenever a tree tries to grow (using bone meal/natural tick/whatever), the sapling disappears, but the tree doesn't get spawned in.
Tree is a structure, AFAIK, so maybe your latest fixes have broken it (not sure about previous versions, because I only played creative before)

**Comment by AntMCDev** [comment]
Oh? It definitely used to work before the latest changes (at least in my survival world) - will take a look into it

**Comment by AntMCDev** [comment]
Ok, found it. Was thankfully a simple fix - but I hope that's the only one (just checking for anything else that may also fail due to that logic). Thanks for catching that, it was quite the game-breaking bug! Just releasing v2.3 on Curseforge now

**Comment by AntMCDev** [comment]
All looks fine now - checked anything else that may use that logic (kelp, sea pickles, chorus plants etc) and all seem to work fine in my testing world. Thanks for finding that issue - definitely the worst one yet!

**Comment by AlexProGear** [comment]
I'm sorry to inform you, but after additional testing I've found that red/brown mushrooms and crimson/warped fungi don't grow either

**Comment by AntMCDev** [comment]
Just uploaded v2.4 to Curseforge which fixes the issues with mushrooms and crimson/warped fungus not growing into their respective features. Knew I was forgetting to test something :)

**Comment by AlexProGear** [comment]
That's great! Thanks again :)
