### ISSUE TITLE
Option to allow nether structures to generate blocks

### ISSUE THREAD

**Issue by MattiDragon** [AntMCDev/MCSkyblock#11]
It'd be nice to have them generate blocks. I feel like it works well like that in many skyblock modpacks. Makes it so you don't have to look for arbitrary boxes

**Comment by AntMCDev** [comment]
I have just added Nether Fortress generation in the latest version of the mod available on Curseforge (v2.0.1 for Minecraft 1.19) - use the generateFortress=true property for this. Thanks for the feedback

**Comment by MattiDragon** [comment]
What about bastions?

**Comment by AntMCDev** [comment]
I will consider adding support for bastion generation in a future update - though it will probably take a while as it's got a very different way of generating the strutures that I will have to look into re-enabling. Also, it doesn't have too much utility that I can think of (beyond spawning blocks - which can be obtained through other methods anyway), unlike Nether fortresses which have increased blaze spawns>

So, it's something I'll look into, but it won't likely be added in a while

**Comment by AntMCDev** [comment]
Ok, I've just released v2.0.2 on Curseforge with the following configurable properties for structures generated in the same way as bastions:

- generateAncientCity
- generateBastion
- generatePillagerOutpost

Also added functionality to generate end gateways when defeating the ender dragon:
- generateEndGateways

All those properties default to false, so you'll need to set to true to enable them in the mcskyblock-common.toml file. This hasn't been tested too thoroughly - but seems to be working from a brief one-over.
