### ISSUE TITLE
[Bug] Moss does not spread on 1.19.2 

### ISSUE THREAD

**Issue by JosephMillsAtWork** [AntMCDev/MCSkyblock#22]
After upgrading my world. Moss does not seem to spread with bonemeal. I noticed this when using my dirt farm (stone -> moss -> podzol -> blast chamber -> dirt )

**Comment by AntMCDev** [comment]
Resolved in v2.0.10

**Comment by JosephMillsAtWork** [comment]
@AntMCDev  thanks I'll Download and take a look. I was using 2.0.9 after looking.
