### ISSUE TITLE
[Topic] Next Versions release Checklist.

### ISSUE THREAD

**Issue by JosephMillsAtWork** [AntMCDev/MCSkyblock#28]
## Proposed Changes

**_Please note that this is a work in progress and is up for debate_**

The goal is to be able to have a double chest of all items no matter how the settings are setup. 

Example: Disabling end city structures. Enables Shulker shells from cleric

* One should also be able to complete the [blaze and caves advancements](https://www.planetminecraft.com/data-pack/blazeandcave-s-advancements-pack-1-12/)  with any settings. 

**Generator** 

* Make the generator do all the work when it  comes to structures. 
* Add a way to have custom structures from other mods
* Faster generation
* New Setting for disable and enabling structures. If we still need the bounding box maybe we can make that happen but I would think that if the end user says disable nether fortress they are not even wanting the bounding boxes.  

**Trading**

There will be a new mod soon that will have new villagers in the game.  Please see this [repo](for more details)

* Removal of the following trades.
    * Reinforced deep slate will be removed from masons. (ancient city)
    * Heart of the sea from wandering traders. (craft-able now)
    * Shulker shells from cleric (The end. shulker farms are easy now a days)
    * Music disks from the wandering trader. (New villager same the record man sells all records)
    * End portal frames from wandering trader. (No need as stronghold and custom structure now has it)
    * Lava bucket from wandering trader. (One can get lava from the runned portals. Or we can add the bonus chest)
    * Sponge from wandering trader (Ocean monuments have these now)
        
* New Trades
   * 64 iron will get you 1 raw iron (Jewelry maker)
   * 64 copper will get you 1 raw copper. (Jewelry maker)
   * 64 gold gets you 1 raw gold .
   * all four of the two tall flowers can be bought from the wandering trader.
   * With all the new villager types there is a separate page for all these trades [Add Link]

**Loot**

* Removal
    * witches drop nether wart.(can get from fortress and custom structures)
    * drowned's drop gold. (Gold can be made with pigman farms)
    * phantom -> elytra (You can get from the end)
    * Piglins drop nether rack. (craft-able)
    * Piglins ancient debris (withers dropnow)
    * HOV for diamonds (diamonds can be found in ancient cities and shipwrecks ect )
    * Budding amethyst (we can make geos spawn now.) 

* Added
    * Withers drop ancient debris (33% chance ? maybe should be higher.)
    * Husks drop sand (50%)
    * Tropical fish drop coral fans

**Crafting**

New: 
 
  * Red sand can be crafted with 8 sand and a red dye
  * All coral blocks can now be crafted with the 2x2 of the coral fan.
  * nether rack can now be crafted from 2x2 weeping vines
  * Heart of the sea can now be crafted from one nether star four sea lanterns and four dark prismarine
  * Kelp can be crafted from a 2x2 of sea grass. 
  * Spore blossom can now be crafted from flowering azalea and four pieces of moss.   

Removed: 
   * mycelium has been removed
   * grass has been removed. (spawn island, starts out as grass)
   * toml config has been removed and replaced with json. Includes Gui.
   * Change default runtime mem to 1G

**Misc**

* New advancements for mcskyblock. 
* Change license in fabric-mod to be MIT and add m_jimmer as a member. 
* Added mod menu integrations
* New mappings to official mojang mappings
* lay foundations for making the mod fabric or forge.
* Preset has be renamed to mcskyblock:skyblock_preset
* Seek out others that speak other languages and ask for help with translations.
* Removal of lib toml4j and added modmenu and cloth config. 
* Made gradlew executable for mac, gnu/linux and bsd users
* Renamed asset folder to match modid
* Added misc static variables for better portability.
* Create list of mods to add to make mod pack.

**Comment by AntMCDev** [comment]
Ok, so the reason behind the bounding box was originally a feature request a while back - some users wanted witch huts, fortresses and monuments to spawn without having to mine up all the blocks, while still being able to spawn the relevant mobs. Admittedly the way it currently does that is very hacky, but it does work - possibly room for improvement though.

As for the changes, for the most part I think those are good ideas. However considering the goal is "The goal is to be able to have a double chest of all items no matter how the settings are setup" wouldn't quite apply with some of the removals. Possible we keep as-is (or make harder, but not impossible) if the relevant structures are disabled and remove those options if they're enabled.

1) **"Reinforced deep slate will be removed from masons. (ancient city)"**, **"Sponge from wandering trader (Ocean monuments have these now)"**, **"Lava bucket from wandering trader. (One can get lava from the runned portals. Or we can add the bonus chest)"**, **"phantom -> elytra (You can get from the end)"**, **"HOV for diamonds (diamonds can be found in ancient cities and shipwrecks ect )"**, **"Budding amethyst (we can make geos spawn now.)"**,  **"witches drop nether wart.(can get from fortress and custom structures)"** - If structures are disabled, you wouldn't be able to get a double chest of those.

2) **"drowned's drop gold. (Gold can be made with pigman farms)"** - Lets say you're playing with no custom structures, how would you get to the nether to be able to get nether wart / gold? Current progression would be getting a witch to splash potion another witch + golden apple on a witch to get a villager, this enables aquiring emeralds which can be traded with the wandering trader for a lava bucket to make a nether portal.

3) **"mycelium has been removed"** - unsure on the rationale of this one, there's no way to get mycelium even if all vanilla structures are enabled (could move to a dedicated villager maybe). Seems antithetical to the double chest of items goal to just remove it completely

4) **"grass has been removed. (spawn island, starts out as grass)"** - might be tricky if someone decides to do a one-block start, tree log might cause it to revert to dirt before you have time to cut the log down.

Final thoughts on this, if we're making these new villagers core to being able to get all the items / achievements in the game, would it not make more sense to store them in the mod itself? If not, then it would probably be worth making the base mod have a dependency on that villagers mod at least.
