### ISSUE TITLE
[BUG] in locate structure development 

### ISSUE THREAD

**Issue by JosephMillsAtWork** [AntMCDev/MCSkyblock#31]
If there is a structure that is not enabled and one uses the internal command to locate it. This can have a computer with low ram lockup.

This will change with bounding box change.  But I suggest we add a mixin to the command and just see if it's enabled.  

We could also override in other places. 

I say if and when I make the changes for bounding boxes and this still happens. We will have a backup plan.

**Comment by AntMCDev** [comment]
A mixin wasn't neccessary - the locate command actually calls a method in the chunk generator, so we just needed to override in there. That's pushed to develop-1.19. Worth double checking, but seems to work from my testing
