### ISSUE TITLE
[Feature] New command for "locate island skyblock:BIOME_ID"  needed 

### ISSUE THREAD

**Issue by JosephMillsAtWork** [AntMCDev/MCSkyblock#40]
This is not a must have but a nice to have.

**Comment by JosephMillsAtWork** [comment]
Maybe should be called locateIsland

**Comment by AntMCDev** [comment]
Pushed to develop-1.19 (still a WIP) - currently the command is just /locate-island and only locates the closest (provided it's been generated). Will add a biome filter arg in the future.
