### ISSUE TITLE
[Feature] Add config presets

### ISSUE THREAD

**Issue by AntMCDev** [AntMCDev/MCSkyblock#47]
Add general preset modes that override all other config types, e.g: technical preset [island start radius: 1, sub islands: false, structures: false], easy preset [island start radius: 10, sub islands: true, structures: true], custom [defer to custom config options]

**Comment by JosephMillsAtWork** [comment]
I like this idea.

**Comment by JosephMillsAtWork** [comment]
Closed with a number of great presets
