### ISSUE TITLE
[Todo] server-client config syncing

### ISSUE THREAD

**Issue by AntMCDev** [AntMCDev/MCSkyblock#49]
Make sure that config syncing works between the logical client and logical server if they're on the same machine - but if it's a remote server, config should ONLY be modifiable on there - we don't want clients modifying server properties in a multiplayer environment! I don't think there's any client properties at the moment, so might be able to just disable config on clients connected to remote machines altogether.

**Comment by AntMCDev** [comment]
Might be worth writing a way of interfacing with server properties as a client. Could use a custom command which makes sure the user is a sysadmin on the command source stack (or possibly even hook into the cloth config save mechanism if they're a sysadmin - serialize the config, send over the network, deserialize and set on the server).

**Comment by JosephMillsAtWork** [comment]
This has been fixed at the config re-factor to one file right ?

**Comment by AntMCDev** [comment]
Fixed
