### ISSUE TITLE
architectury todo or not (revert to fabric only)

### ISSUE THREAD

**Issue by JosephMillsAtWork** [AntMCDev/MCSkyblock#60]
Example branch dev 1.19

From what I read in the docs it does not match up. Not sure if this is a primitive types deal or what. 

From what the docs say this is how it is _supposed_ to work. 

Create a common directory with name space. 

Example:   com.foo.bar.**common**

Now make a [fabric, forge] folder to match.

Example:   

com.foo.bar.**common.fabric**

com.foo.bar.**common.forge**

Add a class that you want _fabric_ or _forge_ to overwrite in _common_

com.foo.bar.**common.SomeClass**

```java
public class SomeClass {      
    // This must be a **public static** method.
    @ExpectPlatform
    public static Path getConfigDirectory() {
        // Just throw an error, the content should get replaced at runtime.
        throw new AssertionError();
    }
}
```

Now in our fabric class.

com.foo.bar.common.**fabric.SomeClassImpl**

```java
public class SomeClassImpl {
    public static Path getConfigDirectory() {
        return FabricLoader.getInstance().getConfigDir();
    }
}
```

Forge 

com.foo.bar.common.**forge.SomeClassImpl**

```java
public class SomeClassImpl {
    public static Path getConfigDirectory() {
        return FMLPaths.CONFIGDIR.get();
    }
}
```

com.foo.bar.**common.Main**
```java
        System.out.println( SomeClass.getConfigDirectory().toAbsolutePath().normalize().toString());
```

Issues:

- So one of the issues is this does not always work.
- Next is the runtime speeds. 
- There is also the issue of code duplication. For this project configs come to mind. 
- updating one object means that you must update all the rest. 
- it is confusing.
- seems like all values need to be interfaced would need to be lambda for each get? 
 
 
 Let me know what you think.

**Comment by AntMCDev** [comment]
Architectury seems like a possibly unnecessary step to me. If the stuff in common is platform-independent (which it should be), then there's not really any cause to do this _"Add a class that you want fabric or forge to overwrite in common"_.

As for the runtime speeds, I'm not sure why this would affect it - unless it's doing something very odd - should be compile-time only, then the compiled JAR is just run? Switch code on-the-fly sounds horribly inefficient if that's what it's doing. Building class files at compile time really isn't hard (ASM, BCEL etc do that all the time) - so I have no idea why the fabric/forge specific classes wouldn't just be built as a composite of the common and platform specific class files.

Code duplication is an issue, yeah. It's unavoidable to a certain extent, but architectury seems to make it much worse than it needs to be.

I think we just embed our common lib into the fabric/forge lib using shadow JAR (like it does for the TOML lib on the old version of the mod - also think you've re-added shadow JAR for this). Then write the platform-specific code under the fabric/forge namespaces accordingly

**Comment by AntMCDev** [comment]
So I think ditch architectury, but keep shadow JAR. That's my opinion at least

**Comment by AntMCDev** [comment]
Let's take project configs for example. Using architectury - you would have to duplicate the entire config at least 3 times (once in common - platform independent, once in fabric, once in forge). At least without architectury - we just need to define the core logic in common - then we ONLY have to write code to fill those values out for forge/fabric. We could even straight-up inherit the common class in the forge/fabric config classes (so we don't have to rewrite all the properties - they'd already be there and accessible from the parent class)

**Comment by AntMCDev** [comment]
The only upside of architectury is that it "abstracts" some of the networking code etc - but it's not like we're doing anything fancy that can't be replicated using what the platforms support by default (especially if we're only targetting 2 platforms) - or even hacking it directly into the core minecraft functionality.

**Comment by JosephMillsAtWork** [comment]
I agree with all the statements above. I reverted the core dev branch and moved everything else over to another branch.  

_"Let's take project configs for example. Using architectury - you would have to duplicate the entire config at least 3 times"_

Yup and it does not work the way that the docs say it is supposed to as well.
