### ISSUE TITLE
Can't run in server because missing clientside mod "Modmenu"

### ISSUE THREAD

**Issue by Laifsyn** [AntMCDev/MCSkyblock#69]

**Comment by AntMCDev** [comment]
Merged mods, like this skyblock mod (both client and server side in a single JAR) require that the contents of that mod - including dependencies - are identical. So, we have 3 solutions:
1) Just stick modmenu on the server.
2) Lower the strictness of the dependency (this might mean that clients ignore the warnings, proceed with running the game only to have it crash).
3) Generate completely separate client and server JARs - with different dependencies (would likely lead to even more confusion that the way it currently works).

Out of these 3 solutions - the one that I think makes the most sense is just sticking modmenu in the server mods folder

**Comment by JosephMillsAtWork** [comment]
I agree with this statement. That is until we get our own gui and thus dropping modmenu and cloth (4.0). 

I consider this issue to be closed.  But maybe we should make a checklist for users so they know that everything is installed.

**Comment by AntMCDev** [comment]
There is a section on curseforge that states the dependencies already (including a link to the dependencies) - along with the errors fabric gives @JosephMillsAtWork
