### ISSUE TITLE
Forge: can not save config file

### ISSUE THREAD

**Issue by JosephMillsAtWork** [AntMCDev/MCSkyblock#71]
**Branch**       develop-1.19-crossplatform
**Platform**   Forge

When testing a mixin for icebergs on the new platforms. I noticed that the icebergs did not generate even though I set to true. 
Something is not saving the data nor changing the values even for runtime. I am not sure if this effects fabric.

**Comment by JosephMillsAtWork** [comment]
More digging shows that it is not the save of the file but the 

```java
Config.INSTANCE
```

that is not getting updated when changing the values

**Comment by JosephMillsAtWork** [comment]
![image](https://user-images.githubusercontent.com/8931995/204564486-80a9d807-6d49-4164-83c5-a6546d17d8d3.png)

**Comment by JosephMillsAtWork** [comment]
```java
            Config.INSTANCE.updateToPreset();
```

is what is causing this.  It is updating to defaults in the call. Conifig,INSTANCE just gets reset at this point.


```java

Config.save()
```

After changing the preset all is fine and it saves correctly. 
We need a better way to disable the presets if the user changes the settings. (change to Custom or something of the sort)

**Comment by AntMCDev** [comment]
Yeah, can do - quickest way would be to serialize the config to bytes - and compare to the INSTANCE bytes, and if there's a mismatch, assume there's a change, set the preset to Custom and then let it continue with it's logic

**Comment by AntMCDev** [comment]
Should just be a couple of lines tops

**Comment by JosephMillsAtWork** [comment]
Or if we could just disable the tabs somehow if preset is not custom

**Comment by AntMCDev** [comment]
Probably more intuitive to have it update to custom. If they change properties, it's pretty much a given they want custom options

**Comment by JosephMillsAtWork** [comment]
I consider this to be closed.  But that said lets add something.  I mean I helped write the mod and didn't get the preset deal.
