### ISSUE TITLE
IcebergFeature never generates 

### ISSUE THREAD

**Issue by JosephMillsAtWork** [AntMCDev/MCSkyblock#72]
Not sure if this is a issue or not.  Seems like it changed when the update to the SkyBlockChunkGenerator.buildSurface() and SkyBlockChunkGeneraor.applyBiomeDecoration()

So maybe we can just remove this option and mixin.

**Comment by AntMCDev** [comment]
Icebergs should still generate in the frozen oceans - I did add a line to set those in applyBiomeDecoration. Though yeah, could just completely remove, plenty of other ways to get ice
