### ISSUE TITLE
DebugScreenOverlay crash's on forge

### ISSUE THREAD

**Issue by JosephMillsAtWork** [AntMCDev/MCSkyblock#73]
DebugScreenOverlay crash's on forge.  

![image](https://user-images.githubusercontent.com/8931995/204577446-1e5e7ef7-e0c8-4d30-90bf-7661cab5cdfc.png)

maybe the size needs to be increased ?

**Comment by JosephMillsAtWork** [comment]
Its odd that it thinks I am trying to join a server when I press f3

**Comment by AntMCDev** [comment]
It's a networking issue. I'm working on it - semi-fixed on my local

**Comment by JosephMillsAtWork** [comment]
@AntMCDev  cool.  please pull when you can. Been testing all the mixins and getting to the point that we are almost ready for a release. :)
