### ISSUE TITLE
Save Data on Geodes 

### ISSUE THREAD

**Issue by JosephMillsAtWork** [AntMCDev/MCSkyblock#74]
There are a lot of geodes that spawn if the option is set.Maybe we want to limit this to say 25 and needs to be at least 125 blocks out from spawn ?

**Comment by AntMCDev** [comment]
Can do - or add a scaling config option (0-100% geode frequency). Then just do something like:
if ((int)Math.round(Math.random()*100) > Config...geodeFrequency) { return; }

So at 50%, that means that half the geodes would spawn for example. Super quick and easy, don't have to persist any data etc

**Comment by AntMCDev** [comment]
Plus, it means no matter how far out you go you can still find geodes, just like other structures/features

**Comment by AntMCDev** [comment]
Done
