### ISSUE TITLE
Ravagers won't drop sculk shrieker

### ISSUE THREAD

**Issue by ghost** [AntMCDev/MCSkyblock#96]
Hey folks,
I've found a bug in your latest version of the mod (3.1.7)
I killed a bunch of ravagers with the associated config line set to true but none of them ever dropped a sculk shrieker. However the advancement did pop up the moment I collected the saddle item.
Please fix this!!

**Comment by AntMCDev** [comment]
Hi, I cannot seem to recreate this issue on my end on Fabric 1.19.2 (mod version 3.1.7). Quickly tested in creative with a looting sword and it dropped fine after a handful of ravagers with that config option set to true and the achievement only seems to trigger when the sculk shrieker is picked up

**Comment by ghost** [comment]
Ok so I did some more testing and found out it works fine in singleplayer and a seperate server I created. Guess it's some client-side issues so I'm gonna make sure there aren't any other mods colliding with that one.
Anyways.. thanks for your quick respond and keep up the good work 😊👍

**Comment by AntMCDev** [comment]
Thanks, please do let us know if the issue arises again though!
