### ISSUE TITLE
[BUG] Achievement override

### ISSUE THREAD

**Issue by Kiryonn** [AntMCDev/MCSkyblock#97]
&emsp;So I love this mod that adds the choice in the menu. Making us choose whether we want to play a skyblock world without having to use a separate Instance is really helpful, time-saving and just more practical.<br>
&emsp;That's why I think it's quite counterproductive to override both Vanilla achievements and Moded ones. By that, I mean that there is not a single achievement other than MCSkyblock ones that are visible.<br>
Here is the list of what I'm using that might be useful:
|Name|Version|
|---|---:|
|Minecraft|1.19.2|
|Fabric|0.14.10|
|Better Advancement|0.2.2.142|
|Advancements Enlarger|0.3.0|

**Comment by AntMCDev** [comment]
Hi, thanks for letting us know. v3.1.8 of this mod should now be available which re-adds the non-skyblock achievements back into the game
